mysql:
  host: 127.0.0.1
  port: 3306
  db: blog_db
  user: root
  password: root
  log_level: dev

logger:
  level: info
  prefix: "[gin-blog]"
  director: log
  show_line: true
  log_in_console: true

system:
  host: "0.0.0.0"
  port: 8080
  env: debug

email:
  host: smtp.qq.com
  port: 587
  user: xxx@qq.com
  passwd: xxx
  default_from_email: xxx
  use_tls: true
  use_ssl: false

qq:
  app_id: xxx
  app_key: xxx
  redirect_url: xxx

jwt:
  secret: xxx
  expire: 3
  issuer: blog