basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: Gin-Blog API 文档
  title: Gin-Blog API 文档
  version: "0.1"
paths:
  /article/{id}:
    get:
      consumes:
      - application/json
      description: 获取文章
      parameters:
      - description: 文章ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"获取成功"}'
          schema:
            type: string
      summary: 获取文章
      tags:
      - Article
  /article/faker:
    post:
      consumes:
      - application/json
      description: 生成文章数据
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"生成文章数据成功"}'
          schema:
            type: string
      summary: 生成文章数据
      tags:
      - Article
  /article/list:
    post:
      consumes:
      - application/json
      description: 获取文章列表
      parameters:
      - description: 页码
        in: body
        name: page
        required: true
        schema:
          type: integer
      - description: 每页数量
        in: body
        name: page_size
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"获取成功"}'
          schema:
            type: string
      summary: 获取文章列表
      tags:
      - Article
  /auth/github:
    get:
      consumes:
      - application/json
      description: Github授权
      produces:
      - application/json
      responses:
        "302":
          description: '{"success":true,"data":{},"msg":"授权成功"}'
          schema:
            type: string
      summary: Github授权
      tags:
      - Auth
  /auth/islogin:
    get:
      consumes:
      - application/json
      description: 判断是否登录
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"判断是否登录"}'
          schema:
            type: string
      summary: 判断是否登录
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: 登录
      parameters:
      - description: email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: password
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: code
        in: body
        name: code
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"登录成功"}'
          schema:
            type: string
      summary: 登录
      tags:
      - Auth
  /auth/login/code:
    get:
      consumes:
      - application/json
      description: 登录验证码
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"登录验证码"}'
          schema:
            type: string
      summary: 登录验证码
      tags:
      - Auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: 退出登录
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"退出登录成功"}'
          schema:
            type: string
      summary: 退出登录
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: 注册
      parameters:
      - description: username
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: password
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: code
        in: body
        name: code
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"注册成功"}'
          schema:
            type: string
      summary: 注册
      tags:
      - Auth
  /auth/register/code:
    get:
      consumes:
      - application/json
      description: 注册验证码
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"注册验证码！请在5分钟内使用！"}'
          schema:
            type: string
      summary: 注册验证码
      tags:
      - Auth
  /auth/reset_pwd/{email}:
    post:
      consumes:
      - application/json
      description: 重置密码
      parameters:
      - description: email
        in: path
        name: email
        required: true
        type: string
      - description: new_password
        in: body
        name: new_password
        required: true
        schema:
          type: string
      - description: code
        in: body
        name: code
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"重置密码成功"}'
          schema:
            type: string
      summary: 重置密码
      tags:
      - Auth
  /auth/reset_pwd_code:
    get:
      consumes:
      - application/json
      description: 重置密码验证码
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"重置密码验证码获取成功"}'
          schema:
            type: string
      summary: 重置密码验证码
      tags:
      - Auth
  /auth/verify/{token}/active/{email}:
    get:
      consumes:
      - application/json
      description: 激活账号
      parameters:
      - description: 激活码
        in: path
        name: token
        required: true
        type: string
      - description: 邮箱
        in: path
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"激活成功"}'
          schema:
            type: string
      summary: 激活账号
      tags:
      - Auth
  /auth/verify/{token}/reset_pwd/{email}:
    get:
      consumes:
      - application/json
      description: 激活重置密码token
      parameters:
      - description: 激活码
        in: path
        name: token
        required: true
        type: string
      - description: 邮箱
        in: path
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"激活成功"}'
          schema:
            type: string
      summary: 激活重置密码token
      tags:
      - Auth
  /image/get_upload_image/{img_name}:
    get:
      consumes:
      - application/json
      description: 获取图片
      parameters:
      - description: 图片名称
        in: path
        name: img_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 图片
          schema:
            type: string
      summary: 获取图片
      tags:
      - 图片
  /image/upload_article_cover_image:
    post:
      consumes:
      - multipart/form-data
      description: 上传文章封面图片
      parameters:
      - description: 文件
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"上传成功"}'
          schema:
            type: string
      summary: 上传文章封面图片
      tags:
      - Upload
  /image/upload_article_image:
    post:
      consumes:
      - multipart/form-data
      description: 上传文章图片
      parameters:
      - description: 文件
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"上传成功"}'
          schema:
            type: string
      summary: 上传文章图片
      tags:
      - Upload
  /user/info:
    get:
      consumes:
      - application/json
      description: 获取用户信息
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"获取成功"}'
          schema:
            type: string
      summary: 获取用户信息
      tags:
      - User
  /user/update_email:
    post:
      consumes:
      - application/json
      description: 更新用户邮箱
      parameters:
      - description: email
        in: body
        name: email
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"更新用户邮箱成功"}'
          schema:
            type: string
      summary: 更新用户邮箱
      tags:
      - User
  /user/update_motto:
    post:
      consumes:
      - application/json
      description: 修改用户motto
      parameters:
      - description: motto
        in: body
        name: motto
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"更新用户motto成功！"}'
          schema:
            type: string
      summary: 修改用户motto
      tags:
      - User
  /user/update_password:
    post:
      consumes:
      - application/json
      description: 修改密码
      parameters:
      - description: new_password
        in: body
        name: new_password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"更新用户密码成功！"}'
          schema:
            type: string
      summary: 修改密码
      tags:
      - User
  /user/update_social_account_csdn:
    post:
      consumes:
      - application/json
      description: 修改用户社交账号
      parameters:
      - description: csdn
        in: body
        name: github
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"更新用户社交账号成功！"}'
          schema:
            type: string
      summary: 修改用户社交账号
      tags:
      - User
  /user/update_social_account_gitee:
    post:
      consumes:
      - application/json
      description: 修改用户社交账号
      parameters:
      - description: gitee
        in: body
        name: github
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"更新用户社交账号成功！"}'
          schema:
            type: string
      summary: 修改用户社交账号
      tags:
      - User
  /user/update_social_account_github:
    post:
      consumes:
      - application/json
      description: 修改用户社交账号
      parameters:
      - description: github
        in: body
        name: github
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"更新用户社交账号成功！"}'
          schema:
            type: string
      summary: 修改用户社交账号
      tags:
      - User
  /user/update_social_account_qq:
    post:
      consumes:
      - application/json
      description: 修改用户社交账号
      parameters:
      - description: qq
        in: body
        name: qq
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"更新用户社交账号成功！"}'
          schema:
            type: string
      summary: 修改用户社交账号
      tags:
      - User
swagger: "2.0"
