basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: Gin-Blog API 文档
  title: Gin-Blog API 文档
  version: "0.1"
paths:
  /article/faker:
    post:
      consumes:
      - application/json
      description: 生成文章数据
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"生成文章数据成功"}'
          schema:
            type: string
      summary: 生成文章数据
      tags:
      - Article
  /article/list:
    post:
      consumes:
      - application/json
      description: 获取文章列表
      parameters:
      - description: 页码
        in: body
        name: page
        required: true
        schema:
          type: integer
      - description: 每页数量
        in: body
        name: page_size
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"获取成功"}'
          schema:
            type: string
      summary: 获取文章列表
      tags:
      - Article
  /auth/github:
    get:
      consumes:
      - application/json
      description: Github授权
      produces:
      - application/json
      responses:
        "302":
          description: '{"success":true,"data":{},"msg":"授权成功"}'
          schema:
            type: string
      summary: Github授权
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: 登录
      parameters:
      - description: email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: password
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: code
        in: body
        name: code
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"登录成功"}'
          schema:
            type: string
      summary: 登录
      tags:
      - Auth
  /auth/login/code:
    get:
      consumes:
      - application/json
      description: 登录验证码
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"登录验证码"}'
          schema:
            type: string
      summary: 登录验证码
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: 注册
      parameters:
      - description: username
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: password
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: code
        in: body
        name: code
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"注册成功"}'
          schema:
            type: string
      summary: 注册
      tags:
      - Auth
  /auth/register/code:
    get:
      consumes:
      - application/json
      description: 注册验证码
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"注册验证码！请在5分钟内使用！"}'
          schema:
            type: string
      summary: 注册验证码
      tags:
      - Auth
  /auth/reset_pwd/{email}:
    post:
      consumes:
      - application/json
      description: 重置密码
      parameters:
      - description: email
        in: path
        name: email
        required: true
        type: string
      - description: new_password
        in: body
        name: new_password
        required: true
        schema:
          type: string
      - description: code
        in: body
        name: code
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"重置密码成功"}'
          schema:
            type: string
      summary: 重置密码
      tags:
      - Auth
  /auth/reset_pwd_code:
    get:
      consumes:
      - application/json
      description: 重置密码验证码
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"重置密码验证码获取成功"}'
          schema:
            type: string
      summary: 重置密码验证码
      tags:
      - Auth
  /auth/verify/{token}/active/{email}:
    get:
      consumes:
      - application/json
      description: 激活账号
      parameters:
      - description: 激活码
        in: path
        name: token
        required: true
        type: string
      - description: 邮箱
        in: path
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"激活成功"}'
          schema:
            type: string
      summary: 激活账号
      tags:
      - Auth
  /auth/verify/{token}/reset_pwd/{email}:
    get:
      consumes:
      - application/json
      description: 激活重置密码token
      parameters:
      - description: 激活码
        in: path
        name: token
        required: true
        type: string
      - description: 邮箱
        in: path
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"激活成功"}'
          schema:
            type: string
      summary: 激活重置密码token
      tags:
      - Auth
swagger: "2.0"
